global using Application.Commands;
global using Application.DTOs;
global using Application.DTOs.Identity;
global using Core.Abstractions;
global using FluentValidation;
global using MediatR;
global using Microsoft.AspNetCore.Http;
global using System.Collections.Generic;
global using System.Threading.Tasks;
